/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import controlador.GerenciadorIG;
import controlador.TableModelUsuario;
import javax.swing.JOptionPane;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author 2023122760123
 */
public class FramePrincipal extends javax.swing.JFrame {
    private DialogUsuario dialogUsuario = null;
    private String nomeServer;
    private String nomeUsuario;
    private TableModelUsuario tableModel;
    private Map<String, Integer> contadorMensagens = new HashMap<>();
    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal(TableModelUsuario tableModel) {
        this.tableModel = tableModel;
        initComponents();
        tabela.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        textFieldMensagem = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnRelatorio = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        textFieldServidor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textFieldUsr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Usuários Online"
            }
        ));
        jScrollPane1.setViewportView(tabela);

        textArea.setColumns(20);
        textArea.setRows(5);
        textArea.setFocusable(false);
        jScrollPane2.setViewportView(textArea);

        jLabel1.setText("Nova Mensagem:");

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnRelatorio.setText("Relatório");
        btnRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelatorioActionPerformed(evt);
            }
        });

        jLabel2.setText("Servidor:");

        textFieldServidor.setForeground(new java.awt.Color(255, 0, 0));
        textFieldServidor.setText("Servidor");
        textFieldServidor.setFocusable(false);

        jLabel3.setText("Seu Usuário:");

        textFieldUsr.setForeground(new java.awt.Color(0, 0, 204));
        textFieldUsr.setText("Usuário");
        textFieldUsr.setFocusable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(177, 177, 177)
                        .addComponent(btnEnviar)
                        .addGap(18, 18, 18)
                        .addComponent(btnRelatorio)
                        .addGap(0, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldMensagem)
                            .addComponent(textFieldServidor)
                            .addComponent(textFieldUsr))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldServidor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldUsr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnRelatorio))
                .addGap(0, 27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setNomeServer(String nomeServer) {
        this.nomeServer = nomeServer;
    }

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        dialogUsuario = GerenciadorIG.getInstancia().abrirCadastro();
        nomeUsuario = dialogUsuario.getNomeUsuario();
        textFieldUsr.setText(nomeUsuario);
        textFieldServidor.setText(nomeServer);
    }//GEN-LAST:event_formComponentShown

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String msg = textFieldMensagem.getText();
        
        if(msg.isEmpty()){
            JOptionPane.showMessageDialog(null, "Insira a mensagem a ser enviada");
            textFieldMensagem.requestFocus();
        } else{
            msg = "("+textFieldUsr.getText()+"): "+ msg;
            String resposta = GerenciadorIG.getInstancia().getGerChat().enviarMensagem(msg);
            
            textArea.setText(resposta);
            textFieldMensagem.setText("");
            textFieldMensagem.requestFocus();
            if (nomeUsuario != null && !nomeUsuario.isEmpty()) {
                contadorMensagens.put(nomeUsuario, contadorMensagens.getOrDefault(nomeUsuario, 0) + 1);
            }
        }
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnRelatorioActionPerformed(java.awt.event.ActionEvent evt) {                                             
        StringBuilder relatorio = new StringBuilder();
        relatorio.append("Relatório de Mensagens Enviadas por Usuário:\n\n");
        if (contadorMensagens.isEmpty()) {
            relatorio.append("Nenhuma mensagem enviada ainda.\n");
        } else {
            for (Map.Entry<String, Integer> entry : contadorMensagens.entrySet()) {
                relatorio.append(entry.getKey()).append(": ")
                        .append(entry.getValue()).append(" mensagem(ns)\n");
            }
        }
        JOptionPane.showMessageDialog(this, relatorio.toString(), "Relatório", JOptionPane.INFORMATION_MESSAGE);
    }   
    
    public void atualizarMensagens() {
        textArea.setText(GerenciadorIG.getInstancia().getGerChat().enviarMensagem("ATT"));
    }
    
    public void atualizarUsuarios(boolean condicao){
        tableModel.Atualizar(nomeUsuario, condicao);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnRelatorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabela;
    private javax.swing.JTextArea textArea;
    private javax.swing.JTextField textFieldMensagem;
    private javax.swing.JTextField textFieldServidor;
    private javax.swing.JTextField textFieldUsr;
    // End of variables declaration//GEN-END:variables

}
